### ISSUE TITLE
The meaning of "ImgBot <3 open source" ？

### ISSUE THREAD

**Issue by sogeisetsu** [imgbot/Imgbot#1052]
The free version of imgbot prompts "Unlimited public repos. Unlimited Users.", which is easy to understand. But I don't understand what is called "ImgBot <3 open source". Can you give me a brief explanation?

![](https://suyuesheng-biaozhun-blog-tupian.oss-cn-qingdao.aliyuncs.com/blogimg/20211106220316.png)

**Comment by VixieTSQ** [comment]
Pretty sure the heart emoticon stands for 'loves' aka 'ImgBot loves open source' which here I don't think means anything but exactly that.

**Comment by sogeisetsu** [comment]
> Pretty sure the heart emoticon stands for 'loves' aka 'ImgBot loves open source' which here I don't think means anything but exactly that.

It turns out that "<3" is an emoji. Maybe I am a staid person. I thought it was a mathematical symbol.🤔 I was still thinking about what mathematical meaning it represents.  😂
