### ISSUE TITLE
Imgbot not making the initial PR

### ISSUE THREAD

**Issue by navendu-pottekkat** [imgbot/Imgbot#1061]
I have installed Imgbot on [one of my repos](https://github.com/navendu-pottekkat/navendu-pottekkat.github.io) yesterday and it still hasn't made the initial PR with optimised image as mentioned.

<img width="566" alt="Screenshot 2021-11-15 at 10 44 43 AM" src="https://user-images.githubusercontent.com/49474499/141726329-08ba67af-682f-49c2-891e-e74e5d84700e.png">
<img width="774" alt="Screenshot 2021-11-15 at 10 44 35 AM" src="https://user-images.githubusercontent.com/49474499/141726339-293a2e15-7e57-41b1-b249-9f1ef5d642f2.png">

Is this expected? Does it take this long for it to kick in? Or, am I missing something?

**Comment by GrigoreMihai** [comment]
it does not usually take this long, you can try to request a new optimization from here: https://imgbot.net .

**Comment by navendu-pottekkat** [comment]
Okay. I removed the bot and installed it again now.

Oh, I did not know we could login and request a new optimisation. Will try that if this fails.

**Comment by navendu-pottekkat** [comment]
@GrigoreMihai I have tried requesting multiple times. Still no luck.

**Comment by GrigoreMihai** [comment]
@navendu-pottekkat I checked it on the server logs and everything worked as expected the first optimization started for your repository at maximum one hour after your previous message. I see that the pr was also opened, it should always work at least this fast, but usually even sooner, when you initially tried the app there were some delays indeed but they should not appear anymore. Let me know if everything is working now ?

**Comment by obfuscatedgenerated** [comment]
@GrigoreMihai I am also having this issues even after re-requesting. Could you please check the server logs for my account?

**Comment by navendu-pottekkat** [comment]
It is working fine now I guess. But there was an initial lag which caused me to open the issue. Now I have made multiple requests and Imgbot had made multiple PRs as well.

**Comment by obfuscatedgenerated** [comment]
It doesn't work for me still. There is the chance that no optimisations need to be made, but I doubt that considering that the image files are bigger than they are displayed.

**Comment by obfuscatedgenerated** [comment]
It finally happened. That's a pretty big delay though (7 hours)
