### ISSUE TITLE
[BUG] TLS misconfiguration

### ISSUE THREAD

**Issue by webknjaz** [imgbot/Imgbot#1064]
Currently, after installing and authenticating, the user gets redirected to `https://imgbot.net/winning/` and sees a big red warning from Chrome that this website is not to be trusted.

The TLS certificate that is being presented by the server is issued for `*.netlify.app` CN, not for `imgbot.net` which is the reason it behaves like this.

**Comment by GrigoreMihai** [comment]
are you still seeing this error ? I checked the site on multiple browsers but I can not replicate the warning .

**Comment by webknjaz** [comment]
It's okay now. The returned certificate has `*.imgbot.net` for me.
