### ISSUE TITLE
Manually Trigger optimization 

### ISSUE THREAD

**Issue by PatelN123** [imgbot/Imgbot#1121]
Hey, 

I am on the Student plan and I have linked ImgBot to a private repository. When I try and trigger it from the website, I have no option. 
How do I force it to optimize the images?

**Comment by GrigoreMihai** [comment]
> Hey,
> 
> I am on the Student plan and I have linked ImgBot to a private repository. When I try and trigger it from the website, I have no option. How do I force it to optimize the images?

Hello, sorry for the late reply, you mean that when you access this page: https://imgbot.net/app/ you see the repository listed but not the the button to "Request new optimization" ? If that is the case please send us the name of the repository to check what is happening. (You can also try, if this is the case, to remove the repo from the app settings on github and add it again)

**Comment by PatelN123** [comment]
Thank you.
