### ISSUE TITLE
How long does imgbot take to make a pr?

### ISSUE THREAD

**Issue by 3prm3** [imgbot/Imgbot#1126]

**Comment by KendallDoesCoding** [comment]
It takes about 5-10 hours, maximum 15-20 hours. It would be great if the PR can open instantly as it will help with making releases.

**Comment by 3prm3** [comment]
Ok, thanks

**Comment by Sussy-OS** [comment]
It feels like it takes forever. I wish they made a progress checker so you could see what is happening in real time, so it's like 'Oh, this is compressing this, and the counter here says it will take this long to finish, and there are so many done, and so many to go, ect'

**Comment by KendallDoesCoding** [comment]
> It feels like it takes forever. I wish they made a progress checker so you could see what is happening in real time, so it's like 'Oh, this is compressing this, and the counter here says it will take this long to finish, and there are so many done, and so many to go, ect'

Many people use it at once, and that's a restriction by GitHub, I think, so it takes a couple hours to scan the code, but I get ya.
