### ISSUE TITLE
imgbot seems not work

### ISSUE THREAD

**Issue by kings1990** [imgbot/Imgbot#1205]
Link:[https://github.com/dromara/fast-request](https://github.com/dromara/fast-request)

I have install imgbot to my project and have add the config,  but imgbot seems can not give pr to me! 

<img width="1332" alt="image" src="https://user-images.githubusercontent.com/8969637/183347007-bf00aa67-b614-4137-9a4e-b5c6580874ef.png">

<img width="1073" alt="image" src="https://user-images.githubusercontent.com/8969637/183347174-f263452d-f4c8-4f89-b8c8-47cae827403a.png">

**Comment by GrigoreMihai** [comment]
Hello, to make it work please remove comments from the configuration file, also note that configurable pull request title and body are only available for paid plans. Remove also the `schedule`field if you want the pr to be instant and not weekly as you set it up. The `ignoreFiles` can also be removed if not used. I tested here and everything is working as expected: https://github.com/GrigoreMihai/fast-request/pull/1 . Also change the `minKBReduced` to `0` to be sure you have the minimum optimization to open a pull request, eg: https://github.com/GrigoreMihai/fast-request/blob/master/.imgbotconfig 


Let us know if you receive the optimization after doing the changes in the `.imgbotconfig` file. Thank you.

**Comment by kings1990** [comment]
I have change the config like example 
https://github.com/dromara/fast-request/blob/master/.imgbotconfig

And have click this button
<img width="928" alt="image" src="https://user-images.githubusercontent.com/8969637/184297255-36a69e48-c61f-4df3-88d5-3ae5139be1b3.png">
 It seems still no PR, does it take too long to provide PR?

**Comment by kings1990** [comment]
Hello, is there any other solution?

**Comment by kings1990** [comment]
<img width="920" alt="image" src="https://user-images.githubusercontent.com/8969637/184518411-84d042fb-e2fe-433d-a8c8-60dd0dce6afc.png">

**Comment by kings1990** [comment]
Need help

**Comment by kings1990** [comment]
Six days, still no pr!!!

**Comment by GrigoreMihai** [comment]
Hello, we checked this issue and there is a limit on how many images we can optimize in a single repository depending on the number of images, size and format. We are currently reviewing this issue and we will do the necessary updates so  we can handle bigger repositories. We will let you know when we fix this.

**Comment by GrigoreMihai** [comment]
Hello @kings1990  , we did some updates and got a pr on a fork of your repository https://github.com/GrigoreMihai/fast-request/pulls . You can request two optimization (half of hour apart from each other) for your repository from here: https://imgbot.net/ and you should get a pr in a few hours depending on the current workload.

**Comment by GrigoreMihai** [comment]
I see that you got a pr here: https://github.com/dromara/fast-request/pull/105 .
