### ISSUE TITLE
Imgbot doesn't seem to work when there are a lot of pictures

### ISSUE THREAD

**Issue by RavelloH** [imgbot/Imgbot#1209]
repo url: https://github.com/RavelloH/PSGameSpider  

I added imgbot to my repo five days ago, but it hasn't given me PR until now.   
I didn't set .imgbotconfig for it, and I added imgbot to another repository at the same time five days ago. It works well.  
This repo contains about 6700 pictures. Is it normal for imgbot not to work at this time?  
Thank you for your answer!

**Comment by kings1990** [comment]
Same for me!

**Comment by kings1990** [comment]
用这个吧https://github.com/marketplace/actions/image-actions

**Comment by RavelloH** [comment]
> 用这个吧https://github.com/marketplace/actions/image-actions

@kings1990 感谢分享！  
我看了下imgbot的管理页面(https://imgbot.net/app/ )，请求倒是每天都在触发，但是没给PR T_T  
可能确实是图片多了就处理不过来

**Comment by GrigoreMihai** [comment]
Hello, we checked this issue and there is a limit on how many images we can optimize in a single repository depending on the number of images, size and format. We are currently reviewing this issue and we will do the necessary updates so we can handle bigger repositories. We will let you know when we fix this. 

@RavelloH in your case the repository is very big, over the limit our containers can handle right now we will review this use cases after we fix the above mentioned issue and will let you know if we update to support up to repositories of your's size.

**Comment by RavelloH** [comment]
> Hello, we checked this issue and there is a limit on how many images we can optimize in a single repository depending on the number of images, size and format. We are currently reviewing this issue and we will do the necessary updates so we can handle bigger repositories. We will let you know when we fix this.
> 
> @RavelloH in your case the repository is very big, over the limit our containers can handle right now we will review this use cases after we fix the above mentioned issue and will let you know if we update to support up to repositories of your's size.

@GrigoreMihai Thank you for your answer!  
If the repository is too large, it is understandable. After all, my repo is too large...  
However, imgbot works well in other normal repositories. Thank you for this tool!

**Comment by GrigoreMihai** [comment]
Hello @RavelloH , I see that a pull request was opened for your repository https://github.com/RavelloH/PSGameSpider/pull/10 , let me know if everything is ok now so I can close this issue.

**Comment by RavelloH** [comment]
@GrigoreMihai Thank you. It seems to work.   
In addition, is it because the optimized size of the remaining files is too small that only 290 files are updated?

**Comment by GrigoreMihai** [comment]
> @GrigoreMihai Thank you. It seems to work. In addition, is it because the optimized size of the remaining files is too small that only 290 files are updated?

Yes, we skip images that do not gain any size reduction compared to the original.
