### ISSUE TITLE
Imgbot stopped raising PRs on my repo for the last one year

### ISSUE THREAD

**Issue by rahulrai-in** [imgbot/Imgbot#1210]
ImgBot was working fine with my repo until August last year: https://github.com/rahulrai-in/thecloudblog/pulls?q=is%3Apr+is%3Aclosed

I have tried reaching out to support and manually triggering the optimization from the app: https://imgbot.net/app/

I can't seem to figure out what is wrong with it and need help.

**Comment by GrigoreMihai** [comment]
Hello, we checked this issue and there is a limit on how many images we can optimize in a single repository depending on the number of images, size and format. We are currently reviewing this issue and we will do the necessary updates so we can handle bigger repositories. We will let you know when we fix this.

**Comment by GrigoreMihai** [comment]
Hello @rahulrai-in , we did some updates and got a pr on a fork of your repository https://github.com/GrigoreMihai/thecloudblog/pulls . You can request two optimization (half of hour apart from each other) for your repository from here: https://imgbot.net/ and you should get a pr in a few hours depending on the current workload.

**Comment by rahulrai-in** [comment]
Thank you so much for fixing this issue. I received a PR from the bot.
