### ISSUE TITLE
ImgBot not working?

### ISSUE THREAD

**Issue by NihalNavath** [imgbot/Imgbot#1238]
I am installed imgbot almost a month ago for the resp https://github.com/NihalNavath/Nihal-Navath (private) and has plently on images that should have been caught by now, but it never created a pr?

**Comment by GrigoreMihai** [comment]
Hello, sorry for the late reply, we only process private repositories if you have one of the paid plans, if you have one of the paid plans let us what is your github account login name so we can look up for it.

**Comment by NihalNavath** [comment]
Well that was a disspointment, but anyway thanks, closing issue.
