### ISSUE TITLE
[Help] repo didn't receive PR from imgbot

### ISSUE THREAD

**Issue by Pil0tXia** [imgbot/Imgbot#1266]
This is a issue similar to https://github.com/imgbot/Imgbot/issues/88
The previous 2 PRs in my repo from imgbot are all lossless compression. However, It has been 25 days after I received last PR from imgbot. I added "aggressiveCompression" option to config and uploaded multiple images during this time. I tried to request new optimization one imgbot.net but it didn't work. May you please help me figure out where the problem is?
repo: https://github.com/Pil0tXia/imghost
config:
```
{
"schedule": "weekly",
"ignoredFiles": [
"picgo/WEATHERING WITH YOU*"
],
"aggressiveCompression": "true"
}
```
Thank you very much!

**Comment by GrigoreMihai** [comment]
Hello,this is probably related to the new batch threshold update we did a while back. 

I have now updated that to the previous value. Please request two new optimization on `imgbot.net` at a few hours apart from each other.

Let us know if you receive a pr after doing this.

**Comment by Pil0tXia** [comment]
I requested optimizations 16 hrs ago and 5hrs ago, I haven't received a PR yet.

**Comment by Pil0tXia** [comment]
I recieved a [PR](https://github.com/Pil0tXia/imghost/pull/3) just now, which really helps. However, I noticed that some of the pictures were reduced in size only a little bit.
For example, [this image](https://github.com/Pil0tXia/imghost/blob/master/picgo/image-20220926154724920.png) looks like easy to be compressed, but it was compressed for 0.01% and less than 1KB in PR.
I didn't edit threshold in .imgbotconfig. May you please tell me the possible cause?
Thanks again.

**Comment by GrigoreMihai** [comment]
That particular image has a lot of detail in it and if any artifacts would be added from the optimization it will be impossible to read the text. 

You're welcome, I'm glad it worked.
