### ISSUE TITLE
Images are compressed again after being moved

### ISSUE THREAD

**Issue by Pil0tXia** [imgbot/Imgbot#1273]
I moved some pics from one directory to another one (from /picgo to /gallery and /cover), and some of these pics are compressed again in [the next PR](https://github.com/Pil0tXia/imghost/pull/4).
I think it is meaningless to compress them again, because the size reduced was quite small and it affects image quality.
I hope this problem can be fixed.
Thank you.

**Comment by GrigoreMihai** [comment]
Hello, there are a few config options that might help you in this case: https://imgbot.net/docs/#configuration . 

The first one you can try is the `ignoredFiles` options to exclude the files you don't want to optimize. 

You can also use the `minKBReduced` option to setup a higher threshold for the optimization. 

They are both described in the documentation, but feel free to reach out for any questions.

**Comment by Pil0tXia** [comment]
You mean moved images should be manually added to `ignoredFiles` to avoid being compressed again? It may be fussy.
Is there any way to ignore moved files by reading the move operation in git comments? I think it is a reasonable and neccessary feature.
