### ISSUE TITLE
Is it possible to configure imgbot to run on a specific branch?

### ISSUE THREAD

**Issue by Fernal73** [imgbot/Imgbot#1295]
Is it possible to configure imgbot to run on a specific branch, not just main or master?
I'd like to specify development as my branch on which the images are compressed and then I'd merge them into main myself.
Is that possible?

**Comment by GrigoreMihai** [comment]
Hello, sure we have that option available here: https://imgbot.net . You need to log in and select the settings for the particular repository you want to change the default branch. Simply type the branch name under: `Default branch override` and save the changes.

**Comment by Fernal73** [comment]
So there's no way of doing it except in the way above?

You mean to say I can't have anything like this unless the default branch is development? 

![Screenshot_20230110_192256](https://user-images.githubusercontent.com/24714685/211569902-9e1f07e8-a281-4d83-b946-ab80dd465371.jpg)

Need to do an impact analysis of making the default branch something other than main or master ...

**Comment by GrigoreMihai** [comment]
You do not have to change the default branch on your repository, the setting from our site will only tell `imgbot` to act as if the branch you add in the setting is your default branch and open pull requests against that branch. The option is also described here: https://imgbot.net/docs/#configuration .

**Comment by Fernal73** [comment]
Ok. Thank you very much.
