### ISSUE TITLE
get on to 3.0 of Azure Functions and dotnet core

### ISSUE THREAD

**Issue by dabutvin** [imgbot/Imgbot#630]
We are using dotnet 2.2 right now and functions version ~2 and Functions sdk 1.X

Time to upgrade all the things, probably have to do it all at once

**Comment by dabutvin** [comment]
Bump

**Comment by dabutvin** [comment]
bump

**Comment by dlemstra** [comment]
bump

**Comment by kilbouri** [comment]
3.x has reached End of Life. Issue should be upgraded to 4.x.

**Comment by GrigoreMihai** [comment]
> 3.x has reached End of Life. Issue should be upgraded to 4.x.

We are already running on .net6.0: https://github.com/imgbot/Imgbot/blob/master/CompressImagesFunction/CompressImagesFunction.csproj#L3 and the latest azure functions version.
