### ISSUE TITLE
Strip image metadata to save space and add security

### ISSUE THREAD

**Issue by mlissner** [imgbot/Imgbot#810]
I run a small static site that has imgbot enabled. Love it! 

Recently, we got a vulnerability report that we aren't stripping metadata from the images we post on the site. So far, nothing too nasty has slipped through, but since it's a static site, it'd be nice if imgbot did some metadata stripping. I know this wouldn't be a perfect solution except in private git repos, but it'd still be an improvement, since most people aren't going to splelunk into git history to find images with metadata on them.

This would also help with filesize, though perhaps not too much.

Is this something imgbot might consider doing?

**Comment by dabutvin** [comment]
Hi @mlissner 👋 👋 

Can you share a little more info here? Do you have an example image or what specific metadata still exists on your image after compression?

**Comment by mlissner** [comment]
Good to hear from you, @dabutvin. The photo here is a good example: https://free.law/images/hughes.jpeg

If you paste that link into this website, it shows you a lot of metadata that's still on it (CTRL+F for "gimp"):

http://exif.regex.info/exif.cgi

**Comment by cooljeanius** [comment]
I think #1244 is a dup of this

**Comment by mlissner** [comment]
Closing as a dup.
